project_id = "hzcsalwomlnumwurozuz"

[functions.table-data]
verify_jwt = false

[functions.table-sections]
verify_jwt = false

[functions.assigned-prospects]
verify_jwt = true

[functions.move-to-traites]
verify_jwt = true

[functions.migrate-existing-traites]
verify_jwt = true

[functions.send-callback-reminders]
verify_jwt = false

[functions.csv-import]
verify_jwt = true