project_id = "hzcsalwomlnumwurozuz"

[functions.table-data]
verify_jwt = false

[functions.table-sections]
verify_jwt = false

[functions.assigned-prospects]
verify_jwt = true

[functions.move-to-traites]
verify_jwt = true